name: run checks
on: [push, pull_request]

env:
  GODOT_SERVER_URL: https://downloads.tuxfamily.org/godotengine/3.5/beta1/Godot_v3.5-beta1_linux_headless.64.zip
  GODOT_SERVER_BIN: Godot_v3.5-beta1_linux_headless.64
jobs:
  build-server:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install wget
          wget $GODOT_SERVER_URL
          unzip ${GODOT_SERVER_BIN}.zip
          mkdir -p bin
          mv $GODOT_SERVER_BIN bin/godot
          chmod +x bin/godot
      - name: Import
        run: |
          ./bin/godot -d -e -s .github/workflows/test_script.gd || true
          ./bin/godot -d -e -s .github/workflows/test_script.gd 
        timeout-minutes: 5
        continue-on-error: false
      - name: Export pack
        run: |
          ./bin/godot -e --export-pack linux data.pak
          if [ ! -f data.pak ]; then exit 1; fi
        timeout-minutes: 3

