name: run checks
on: [push, pull_request]

env:
  GODOT_SERVER_URL: https://downloads.tuxfamily.org/godotengine/3.5/beta1/Godot_v3.5-beta1_linux_headless.64.zip
  GODOT_SERVER_BIN: Godot_v3.5-beta1_linux_headless.64
jobs:
  build-server:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install wget
          wget $GODOT_SERVER_URL
          unzip ${GODOT_SERVER_BIN}.zip
          mkdir -p bin
          mv $GODOT_SERVER_BIN bin/godot
          chmod +x bin/godot
      - name: Check files consistency
        run: |
          ./bin/godot -d -e -s .github/workflows/test_script.gd >/dev/null 2>&1 || true
          count=$(git ls-files -m | wc -l)
          if [ $count -gt 0 ]; then
            echo "Inconsistent commit. The files "
            git ls-files -m
            echo "are modified by editor. You can do ONE of these:"
            echo "1. If files are needed, open the project in editor,"
            echo "   exit the editor, and commit the files adding to your PR."
            echo "2. If files are NOT needed, add these files to .gitignore,"
            echo "   REMOVE them from the repository and add these changes to your PR."
            exit 1
          fi
      - name: Import
        run: |
          ./bin/godot -d -e -s .github/workflows/test_script.gd || true
          ./bin/godot -d -e -s .github/workflows/test_script.gd 
        timeout-minutes: 5
        continue-on-error: false
      - name: Export pack
        run: |
          ./bin/godot -e --export-pack linux data.pak
          if [ ! -f data.pak ]; then exit 1; fi
        timeout-minutes: 3

